<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get categories by slug
        $featuredCategory = Category::where('slug', 'featured-products')->first();
        $organicCategory = Category::where('slug', 'organic-food')->first();
        $spicesCategory = Category::where('slug', 'spices-herbs')->first();
        $dairyCategory = Category::where('slug', 'dairy-products')->first();
        $beveragesCategory = Category::where('slug', 'beverages')->first();

        // Featured Products (10 products)
        $featuredProducts = [
            [
                'name' => 'Honeycomb Pure Honey',
                'name_bn' => 'চাক ভাঙা খাঁটি মধু',
                'slug' => 'chak-bhanga-pure-honey',
                'description' => 'Natural honeycomb pure honey, completely authentic and unadulterated',
                'description_bn' => 'প্রাকৃতিক চাক ভাঙা খাঁটি মধু, সম্পূর্ণ খাঁটি এবং ভেজালমুক্ত',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 850,
                'original_price' => 1200,
                'category_id' => $featuredCategory->id,
                'stock' => 50,
                'image' => 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 58,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Binni Rice (Premium)',
                'name_bn' => 'বিন্নি চাল (প্রিমিয়াম)',
                'slug' => 'binni-rice-premium',
                'description' => 'Premium quality Binni rice, aromatic and nutritious',
                'description_bn' => 'প্রিমিয়াম মানের বিন্নি চাল, সুগন্ধযুক্ত এবং পুষ্টিকর',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 320,
                'original_price' => 400,
                'category_id' => $featuredCategory->id,
                'stock' => 100,
                'image' => 'https://images.pexels.com/photos/5876662/pexels-photo-5876662.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 42,
                'badge' => '20% off',
                'badge_bn' => '২০% ছাড়',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Jum Pure Turmeric',
                'name_bn' => 'জুমের খাঁটি হলুদ',
                'slug' => 'jum-pure-turmeric',
                'description' => 'Pure turmeric from Jum cultivation, natural and unadulterated',
                'description_bn' => 'জুম চাষের খাঁটি হলুদ, প্রাকৃতিক এবং ভেজালমুক্ত',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 180,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 80,
                'image' => 'https://images.pexels.com/photos/531446/pexels-photo-531446.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 73,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Pure Cow Ghee',
                'name_bn' => 'গরুর খাঁটি ঘি',
                'slug' => 'pure-ghee',
                'description' => 'Pure cow milk ghee, made with completely natural methods',
                'description_bn' => 'খাঁটি গরুর দুধের ঘি, সম্পূর্ণ প্রাকৃতিক পদ্ধতিতে তৈরি',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 1250,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 30,
                'image' => 'https://images.pexels.com/photos/8964561/pexels-photo-8964561.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 35,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Hill Mixed Pickle',
                'name_bn' => 'পাহাড়ি মিক্স আচার',
                'slug' => 'pahari-mixed-pickle',
                'description' => 'Special mixed pickle made with hill ingredients',
                'description_bn' => 'পাহাড়ি উপাদান দিয়ে তৈরি বিশেষ মিক্স আচার',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 280,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 60,
                'image' => 'https://images.pexels.com/photos/7937481/pexels-photo-7937481.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 28,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Kani Rice (Organic)',
                'name_bn' => 'কানি চাল (অর্গানিক)',
                'slug' => 'kani-rice-organic',
                'description' => 'Organic Kani rice, chemical-free and healthy',
                'description_bn' => 'অর্গানিক কানি চাল, রাসায়নিক মুক্ত এবং স্বাস্থ্যকর',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 255,
                'original_price' => 300,
                'category_id' => $featuredCategory->id,
                'stock' => 90,
                'image' => 'https://images.pexels.com/photos/2291599/pexels-photo-2291599.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 49,
                'badge' => '15% off',
                'badge_bn' => '১৫% ছাড়',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Dried Hot Chili',
                'name_bn' => 'শুকনা ঝাল মরিচ',
                'slug' => 'dried-hot-chili',
                'description' => 'Dried hot chili, natural and intensely spicy',
                'description_bn' => 'শুকনা ঝাল মরিচ, প্রাকৃতিক এবং তীব্র ঝাল',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 150,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 70,
                'image' => 'https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 61,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Pure Mustard Oil',
                'name_bn' => 'খাঁটি সরিষার তেল',
                'slug' => 'pure-mustard-oil',
                'description' => 'Pure mustard oil, cold-pressed extraction',
                'description_bn' => 'খাঁটি সরিষার তেল, ঠান্ডা পদ্ধতিতে নিষ্কাশন',
                'unit' => 'ltr',
                'unit_bn' => 'লিটার',
                'price' => 480,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 45,
                'image' => 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 54,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Jum Aromatic Rice',
                'name_bn' => 'জুমের সুগন্ধি চাল',
                'slug' => 'jum-aromatic-rice',
                'description' => 'Aromatic rice from Jum cultivation, naturally grown',
                'description_bn' => 'জুম চাষের সুগন্ধি চাল, প্রাকৃতিক পদ্ধতিতে চাষকৃত',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 375,
                'original_price' => 500,
                'category_id' => $featuredCategory->id,
                'stock' => 85,
                'image' => 'https://images.pexels.com/photos/1810316/pexels-photo-1810316.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 67,
                'badge' => '25% off',
                'badge_bn' => '২৫% ছাড়',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Hill Black Tea',
                'name_bn' => 'পাহাড়ি কালো চা',
                'slug' => 'pahari-black-tea',
                'description' => 'Natural black tea from hill areas, aromatic',
                'description_bn' => 'পাহাড়ি এলাকার প্রাকৃতিক কালো চা, সুগন্ধযুক্ত',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 320,
                'original_price' => null,
                'category_id' => $featuredCategory->id,
                'stock' => 75,
                'image' => 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=400',
                'rating' => 5.00,
                'reviews_count' => 39,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        // Organic Food (5 products)
        $organicProducts = [
            [
                'name' => 'Organic Fresh Vegetables',
                'name_bn' => 'জৈব তাজা সবজি',
                'slug' => 'organic-fresh-vegetables',
                'description' => 'Fresh vegetables grown organically, chemical-free',
                'description_bn' => 'জৈব পদ্ধতিতে চাষকৃত তাজা সবজি, রাসায়নিক মুক্ত',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 150,
                'original_price' => null,
                'category_id' => $organicCategory->id,
                'stock' => 100,
                'image' => 'https://images.pexels.com/photos/1300972/pexels-photo-1300972.jpeg',
                'rating' => 4.80,
                'reviews_count' => 25,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Organic Spinach',
                'name_bn' => 'জৈব পালংশাক',
                'slug' => 'organic-spinach',
                'description' => 'Organic spinach, fresh and nutritious',
                'description_bn' => 'জৈব পালংশাক, তাজা এবং পুষ্টিকর',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 80,
                'original_price' => null,
                'category_id' => $organicCategory->id,
                'stock' => 120,
                'image' => 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg',
                'rating' => 4.90,
                'reviews_count' => 18,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Organic Tomato',
                'name_bn' => 'জৈব টমেটো',
                'slug' => 'organic-tomato',
                'description' => 'Organically grown tomato, fresh and healthy',
                'description_bn' => 'জৈব পদ্ধতিতে চাষকৃত টমেটো, তাজা এবং স্বাস্থ্যকর',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 120,
                'original_price' => 150,
                'category_id' => $organicCategory->id,
                'stock' => 90,
                'image' => 'https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg',
                'rating' => 4.70,
                'reviews_count' => 32,
                'badge' => '20% off',
                'badge_bn' => '২০% ছাড়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Organic Potato',
                'name_bn' => 'জৈব আলু',
                'slug' => 'organic-potato',
                'description' => 'Organic potato, naturally cultivated',
                'description_bn' => 'জৈব আলু, প্রাকৃতিক পদ্ধতিতে চাষকৃত',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 100,
                'original_price' => null,
                'category_id' => $organicCategory->id,
                'stock' => 150,
                'image' => 'https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg',
                'rating' => 4.85,
                'reviews_count' => 45,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Organic Carrot',
                'name_bn' => 'জৈব গাজর',
                'slug' => 'organic-carrot',
                'description' => 'Organic carrot, fresh and sweet',
                'description_bn' => 'জৈব গাজর, তাজা এবং মিষ্টি',
                'unit' => 'kg',
                'unit_bn' => 'কেজি',
                'price' => 90,
                'original_price' => null,
                'category_id' => $organicCategory->id,
                'stock' => 110,
                'image' => 'https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg',
                'rating' => 4.75,
                'reviews_count' => 22,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Spices & Herbs (5 products)
        $spicesProducts = [
            [
                'name' => 'Coriander Powder',
                'name_bn' => 'ধনিয়া গুঁড়া',
                'slug' => 'coriander-powder',
                'description' => 'Pure coriander powder, aromatic and pure',
                'description_bn' => 'খাঁটি ধনিয়া গুঁড়া, সুগন্ধযুক্ত এবং বিশুদ্ধ',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 85,
                'original_price' => null,
                'category_id' => $spicesCategory->id,
                'stock' => 80,
                'image' => 'https://images.pexels.com/photos/1340116/pexels-photo-1340116.jpeg',
                'rating' => 4.95,
                'reviews_count' => 28,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Cumin',
                'name_bn' => 'জিরা',
                'slug' => 'cumin',
                'description' => 'Pure cumin, quality assured',
                'description_bn' => 'খাঁটি জিরা, গুণমান নিশ্চিত',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 95,
                'original_price' => null,
                'category_id' => $spicesCategory->id,
                'stock' => 70,
                'image' => 'https://images.pexels.com/photos/4198921/pexels-photo-4198921.jpeg',
                'rating' => 4.90,
                'reviews_count' => 35,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Black Pepper',
                'name_bn' => 'কালো মরিচ',
                'slug' => 'black-pepper',
                'description' => 'Pure black pepper, intense flavor and spicy',
                'description_bn' => 'খাঁটি কালো মরিচ, তীব্র স্বাদ এবং ঝাল',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 120,
                'original_price' => 140,
                'category_id' => $spicesCategory->id,
                'stock' => 60,
                'image' => 'https://images.pexels.com/photos/4110256/pexels-photo-4110256.jpeg',
                'rating' => 4.88,
                'reviews_count' => 42,
                'badge' => '15% off',
                'badge_bn' => '১৫% ছাড়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Cardamom',
                'name_bn' => 'এলাচ',
                'slug' => 'cardamom',
                'description' => 'Large cardamom, aromatic and pure',
                'description_bn' => 'বড় এলাচ, সুগন্ধযুক্ত এবং খাঁটি',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 180,
                'original_price' => null,
                'category_id' => $spicesCategory->id,
                'stock' => 50,
                'image' => 'https://images.pexels.com/photos/4198939/pexels-photo-4198939.jpeg',
                'rating' => 4.92,
                'reviews_count' => 30,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Bay Leaf',
                'name_bn' => 'তেজপাতা',
                'slug' => 'bay-leaf',
                'description' => 'Dried bay leaf, fragrant and spicy',
                'description_bn' => 'শুকনা তেজপাতা, ঘ্রাণযুক্ত এবং মসলাদার',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 75,
                'original_price' => null,
                'category_id' => $spicesCategory->id,
                'stock' => 90,
                'image' => 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg',
                'rating' => 4.85,
                'reviews_count' => 20,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Dairy Products (5 products)
        $dairyProducts = [
            [
                'name' => 'Pure Yogurt',
                'name_bn' => 'খাঁটি দই',
                'slug' => 'pure-yogurt',
                'description' => 'Pure milk yogurt, sweet-sour and nutritious',
                'description_bn' => 'খাঁটি দুধের দই, টক-মিষ্টি এবং পুষ্টিকর',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 120,
                'original_price' => null,
                'category_id' => $dairyCategory->id,
                'stock' => 40,
                'image' => 'https://images.pexels.com/photos/4397289/pexels-photo-4397289.jpeg',
                'rating' => 4.92,
                'reviews_count' => 38,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Fresh Milk',
                'name_bn' => 'তাজা দুধ',
                'slug' => 'fresh-milk',
                'description' => 'Fresh cow milk, pure and nutritious',
                'description_bn' => 'তাজা গরুর দুধ, খাঁটি এবং পুষ্টিকর',
                'unit' => 'ltr',
                'unit_bn' => 'লিটার',
                'price' => 80,
                'original_price' => null,
                'category_id' => $dairyCategory->id,
                'stock' => 60,
                'image' => 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg',
                'rating' => 4.88,
                'reviews_count' => 45,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Butter',
                'name_bn' => 'মাখন',
                'slug' => 'butter',
                'description' => 'Pure milk butter, smooth and delicious',
                'description_bn' => 'খাঁটি দুধের মাখন, মসৃণ এবং সুস্বাদু',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 280,
                'original_price' => 320,
                'category_id' => $dairyCategory->id,
                'stock' => 35,
                'image' => 'https://images.pexels.com/photos/4551832/pexels-photo-4551832.jpeg',
                'rating' => 4.90,
                'reviews_count' => 25,
                'badge' => '15% off',
                'badge_bn' => '১৫% ছাড়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Cottage Cheese',
                'name_bn' => 'পনির',
                'slug' => 'cottage-cheese',
                'description' => 'Fresh cottage cheese, soft and protein-rich',
                'description_bn' => 'তাজা পনির, নরম এবং প্রোটিন সমৃদ্ধ',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 180,
                'original_price' => null,
                'category_id' => $dairyCategory->id,
                'stock' => 30,
                'image' => 'https://images.pexels.com/photos/821365/pexels-photo-821365.jpeg',
                'rating' => 4.85,
                'reviews_count' => 22,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Cream',
                'name_bn' => 'ক্রিম',
                'slug' => 'cream',
                'description' => 'Milk cream, thick and rich',
                'description_bn' => 'দুধের ক্রিম, ঘন এবং সমৃদ্ধ',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 150,
                'original_price' => null,
                'category_id' => $dairyCategory->id,
                'stock' => 25,
                'image' => 'https://images.pexels.com/photos/7937420/pexels-photo-7937420.jpeg',
                'rating' => 4.80,
                'reviews_count' => 18,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Beverages (5 products)
        $beveragesProducts = [
            [
                'name' => 'Green Tea',
                'name_bn' => 'সবুজ চা',
                'slug' => 'green-tea',
                'description' => 'Green tea, healthy and antioxidant-rich',
                'description_bn' => 'সবুজ চা, স্বাস্থ্যকর এবং অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 280,
                'original_price' => null,
                'category_id' => $beveragesCategory->id,
                'stock' => 70,
                'image' => 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg',
                'rating' => 4.95,
                'reviews_count' => 48,
                'badge' => 'hot',
                'badge_bn' => 'জনপ্রিয়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Coffee Powder',
                'name_bn' => 'কফি পাউডার',
                'slug' => 'coffee-powder',
                'description' => 'Pure coffee powder, aromatic and strong',
                'description_bn' => 'খাঁটি কফি পাউডার, সুগন্ধযুক্ত এবং শক্তিশালী',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 380,
                'original_price' => null,
                'category_id' => $beveragesCategory->id,
                'stock' => 55,
                'image' => 'https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg',
                'rating' => 4.88,
                'reviews_count' => 35,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Herbal Tea',
                'name_bn' => 'ভেষজ চা',
                'slug' => 'herbal-tea',
                'description' => 'Herbal tea, healthy and natural',
                'description_bn' => 'ভেষজ চা, স্বাস্থ্যকর এবং প্রাকৃতিক',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 320,
                'original_price' => 380,
                'category_id' => $beveragesCategory->id,
                'stock' => 60,
                'image' => 'https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg',
                'rating' => 4.82,
                'reviews_count' => 28,
                'badge' => '15% off',
                'badge_bn' => '১৫% ছাড়',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Lemon Tea',
                'name_bn' => 'লেবু চা',
                'slug' => 'lemon-tea',
                'description' => 'Lemon tea, refreshing and flavorful',
                'description_bn' => 'লেবু চা, সতেজ এবং স্বাদযুক্ত',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 220,
                'original_price' => null,
                'category_id' => $beveragesCategory->id,
                'stock' => 80,
                'image' => 'https://images.pexels.com/photos/1484403/pexels-photo-1484403.jpeg',
                'rating' => 4.78,
                'reviews_count' => 32,
                'badge' => 'new',
                'badge_bn' => 'নতুন',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Instant Coffee Mix',
                'name_bn' => 'ইন্সট্যান্ট কফি মিক্স',
                'slug' => 'instant-coffee-mix',
                'description' => 'Instant coffee mix, convenient and delicious',
                'description_bn' => 'ইন্সট্যান্ট কফি মিক্স, সুবিধাজনক এবং সুস্বাদু',
                'unit' => 'gm',
                'unit_bn' => 'গ্রাম',
                'price' => 450,
                'original_price' => null,
                'category_id' => $beveragesCategory->id,
                'stock' => 45,
                'image' => 'https://images.pexels.com/photos/2396220/pexels-photo-2396220.jpeg',
                'rating' => 4.85,
                'reviews_count' => 40,
                'badge' => null,
                'badge_bn' => null,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        // Insert all products
        foreach ($featuredProducts as $product) {
            Product::create($product);
        }

        foreach ($organicProducts as $product) {
            Product::create($product);
        }

        foreach ($spicesProducts as $product) {
            Product::create($product);
        }

        foreach ($dairyProducts as $product) {
            Product::create($product);
        }

        foreach ($beveragesProducts as $product) {
            Product::create($product);
        }
    }
}
